//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/11/2016 2:24:43 PM
namespace AirVinyl.Model
{
    /// <summary>
    /// There are no comments for PersonSingle in the schema.
    /// </summary>
    public partial class PersonSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Person>
    {
        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Person> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Friends in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Person> Friends
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Friends == null))
                {
                    this._Friends = Context.CreateQuery<global::AirVinyl.Model.Person>(GetPath("Friends"));
                }
                return this._Friends;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Person> _Friends;
        /// <summary>
        /// There are no comments for VinylRecords in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.VinylRecord> VinylRecords
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._VinylRecords == null))
                {
                    this._VinylRecords = Context.CreateQuery<global::AirVinyl.Model.VinylRecord>(GetPath("VinylRecords"));
                }
                return this._VinylRecords;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.VinylRecord> _VinylRecords;
    }
    /// <summary>
    /// There are no comments for Person in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PersonId")]
    public partial class Person : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="personId">Initial value of PersonId.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        /// <param name="dateOfBirth">Initial value of DateOfBirth.</param>
        /// <param name="gender">Initial value of Gender.</param>
        /// <param name="numberOfRecordsOnWishList">Initial value of NumberOfRecordsOnWishList.</param>
        /// <param name="amountOfCashToSpend">Initial value of AmountOfCashToSpend.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Person CreatePerson(int personId, 
                    string firstName, 
                    string lastName, 
                    global::System.DateTimeOffset dateOfBirth, 
                    global::AirVinyl.Model.Gender gender, 
                    int numberOfRecordsOnWishList, 
                    decimal amountOfCashToSpend)
        {
            Person person = new Person();
            person.PersonId = personId;
            person.FirstName = firstName;
            person.LastName = lastName;
            person.DateOfBirth = dateOfBirth;
            person.Gender = gender;
            person.NumberOfRecordsOnWishList = numberOfRecordsOnWishList;
            person.AmountOfCashToSpend = amountOfCashToSpend;
            return person;
        }
        /// <summary>
        /// There are no comments for Property PersonId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int PersonId
        {
            get
            {
                return this._PersonId;
            }
            set
            {
                this.OnPersonIdChanging(value);
                this._PersonId = value;
                this.OnPersonIdChanged();
                this.OnPropertyChanged("PersonId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _PersonId;
        partial void OnPersonIdChanging(int value);
        partial void OnPersonIdChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property DateOfBirth in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.DateTimeOffset DateOfBirth
        {
            get
            {
                return this._DateOfBirth;
            }
            set
            {
                this.OnDateOfBirthChanging(value);
                this._DateOfBirth = value;
                this.OnDateOfBirthChanged();
                this.OnPropertyChanged("DateOfBirth");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.DateTimeOffset value);
        partial void OnDateOfBirthChanged();
        /// <summary>
        /// There are no comments for Property Gender in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.Gender Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this.OnGenderChanging(value);
                this._Gender = value;
                this.OnGenderChanged();
                this.OnPropertyChanged("Gender");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.Gender _Gender;
        partial void OnGenderChanging(global::AirVinyl.Model.Gender value);
        partial void OnGenderChanged();
        /// <summary>
        /// There are no comments for Property NumberOfRecordsOnWishList in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int NumberOfRecordsOnWishList
        {
            get
            {
                return this._NumberOfRecordsOnWishList;
            }
            set
            {
                this.OnNumberOfRecordsOnWishListChanging(value);
                this._NumberOfRecordsOnWishList = value;
                this.OnNumberOfRecordsOnWishListChanged();
                this.OnPropertyChanged("NumberOfRecordsOnWishList");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _NumberOfRecordsOnWishList;
        partial void OnNumberOfRecordsOnWishListChanging(int value);
        partial void OnNumberOfRecordsOnWishListChanged();
        /// <summary>
        /// There are no comments for Property AmountOfCashToSpend in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public decimal AmountOfCashToSpend
        {
            get
            {
                return this._AmountOfCashToSpend;
            }
            set
            {
                this.OnAmountOfCashToSpendChanging(value);
                this._AmountOfCashToSpend = value;
                this.OnAmountOfCashToSpendChanged();
                this.OnPropertyChanged("AmountOfCashToSpend");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _AmountOfCashToSpend;
        partial void OnAmountOfCashToSpendChanging(decimal value);
        partial void OnAmountOfCashToSpendChanged();
        /// <summary>
        /// There are no comments for Property Friends in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.Person> Friends
        {
            get
            {
                return this._Friends;
            }
            set
            {
                this.OnFriendsChanging(value);
                this._Friends = value;
                this.OnFriendsChanged();
                this.OnPropertyChanged("Friends");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.Person> _Friends = new global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.Person>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnFriendsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.Person> value);
        partial void OnFriendsChanged();
        /// <summary>
        /// There are no comments for Property VinylRecords in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.VinylRecord> VinylRecords
        {
            get
            {
                return this._VinylRecords;
            }
            set
            {
                this.OnVinylRecordsChanging(value);
                this._VinylRecords = value;
                this.OnVinylRecordsChanged();
                this.OnPropertyChanged("VinylRecords");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.VinylRecord> _VinylRecords = new global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.VinylRecord>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnVinylRecordsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.VinylRecord> value);
        partial void OnVinylRecordsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for VinylRecordSingle in the schema.
    /// </summary>
    public partial class VinylRecordSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<VinylRecord>
    {
        /// <summary>
        /// Initialize a new VinylRecordSingle object.
        /// </summary>
        public VinylRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new VinylRecordSingle object.
        /// </summary>
        public VinylRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new VinylRecordSingle object.
        /// </summary>
        public VinylRecordSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<VinylRecord> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for PressingDetail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.PressingDetailSingle PressingDetail
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PressingDetail == null))
                {
                    this._PressingDetail = new global::AirVinyl.Model.PressingDetailSingle(this.Context, GetPath("PressingDetail"));
                }
                return this._PressingDetail;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.PressingDetailSingle _PressingDetail;
        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.PersonSingle Person
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Person == null))
                {
                    this._Person = new global::AirVinyl.Model.PersonSingle(this.Context, GetPath("Person"));
                }
                return this._Person;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.PersonSingle _Person;
    }
    /// <summary>
    /// There are no comments for VinylRecord in the schema.
    /// </summary>
    /// <KeyProperties>
    /// VinylRecordId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("VinylRecordId")]
    public partial class VinylRecord : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new VinylRecord object.
        /// </summary>
        /// <param name="vinylRecordId">Initial value of VinylRecordId.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="artist">Initial value of Artist.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static VinylRecord CreateVinylRecord(int vinylRecordId, string title, string artist)
        {
            VinylRecord vinylRecord = new VinylRecord();
            vinylRecord.VinylRecordId = vinylRecordId;
            vinylRecord.Title = title;
            vinylRecord.Artist = artist;
            return vinylRecord;
        }
        /// <summary>
        /// There are no comments for Property VinylRecordId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int VinylRecordId
        {
            get
            {
                return this._VinylRecordId;
            }
            set
            {
                this.OnVinylRecordIdChanging(value);
                this._VinylRecordId = value;
                this.OnVinylRecordIdChanged();
                this.OnPropertyChanged("VinylRecordId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _VinylRecordId;
        partial void OnVinylRecordIdChanging(int value);
        partial void OnVinylRecordIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Artist in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Artist
        {
            get
            {
                return this._Artist;
            }
            set
            {
                this.OnArtistChanging(value);
                this._Artist = value;
                this.OnArtistChanged();
                this.OnPropertyChanged("Artist");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Artist;
        partial void OnArtistChanging(string value);
        partial void OnArtistChanged();
        /// <summary>
        /// There are no comments for Property CatalogNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string CatalogNumber
        {
            get
            {
                return this._CatalogNumber;
            }
            set
            {
                this.OnCatalogNumberChanging(value);
                this._CatalogNumber = value;
                this.OnCatalogNumberChanged();
                this.OnPropertyChanged("CatalogNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _CatalogNumber;
        partial void OnCatalogNumberChanging(string value);
        partial void OnCatalogNumberChanged();
        /// <summary>
        /// There are no comments for Property Year in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> Year
        {
            get
            {
                return this._Year;
            }
            set
            {
                this.OnYearChanging(value);
                this._Year = value;
                this.OnYearChanged();
                this.OnPropertyChanged("Year");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _Year;
        partial void OnYearChanging(global::System.Nullable<int> value);
        partial void OnYearChanged();
        /// <summary>
        /// There are no comments for Property PressingDetail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.PressingDetail PressingDetail
        {
            get
            {
                return this._PressingDetail;
            }
            set
            {
                this.OnPressingDetailChanging(value);
                this._PressingDetail = value;
                this.OnPressingDetailChanged();
                this.OnPropertyChanged("PressingDetail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.PressingDetail _PressingDetail;
        partial void OnPressingDetailChanging(global::AirVinyl.Model.PressingDetail value);
        partial void OnPressingDetailChanged();
        /// <summary>
        /// There are no comments for Property Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.Person Person
        {
            get
            {
                return this._Person;
            }
            set
            {
                this.OnPersonChanging(value);
                this._Person = value;
                this.OnPersonChanged();
                this.OnPropertyChanged("Person");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.Person _Person;
        partial void OnPersonChanging(global::AirVinyl.Model.Person value);
        partial void OnPersonChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PressingDetailSingle in the schema.
    /// </summary>
    public partial class PressingDetailSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PressingDetail>
    {
        /// <summary>
        /// Initialize a new PressingDetailSingle object.
        /// </summary>
        public PressingDetailSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PressingDetailSingle object.
        /// </summary>
        public PressingDetailSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PressingDetailSingle object.
        /// </summary>
        public PressingDetailSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PressingDetail> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for PressingDetail in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PressingDetailId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PressingDetailId")]
    public partial class PressingDetail : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PressingDetail object.
        /// </summary>
        /// <param name="pressingDetailId">Initial value of PressingDetailId.</param>
        /// <param name="grams">Initial value of Grams.</param>
        /// <param name="inches">Initial value of Inches.</param>
        /// <param name="description">Initial value of Description.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static PressingDetail CreatePressingDetail(int pressingDetailId, int grams, int inches, string description)
        {
            PressingDetail pressingDetail = new PressingDetail();
            pressingDetail.PressingDetailId = pressingDetailId;
            pressingDetail.Grams = grams;
            pressingDetail.Inches = inches;
            pressingDetail.Description = description;
            return pressingDetail;
        }
        /// <summary>
        /// There are no comments for Property PressingDetailId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int PressingDetailId
        {
            get
            {
                return this._PressingDetailId;
            }
            set
            {
                this.OnPressingDetailIdChanging(value);
                this._PressingDetailId = value;
                this.OnPressingDetailIdChanged();
                this.OnPropertyChanged("PressingDetailId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _PressingDetailId;
        partial void OnPressingDetailIdChanging(int value);
        partial void OnPressingDetailIdChanged();
        /// <summary>
        /// There are no comments for Property Grams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Grams
        {
            get
            {
                return this._Grams;
            }
            set
            {
                this.OnGramsChanging(value);
                this._Grams = value;
                this.OnGramsChanged();
                this.OnPropertyChanged("Grams");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Grams;
        partial void OnGramsChanging(int value);
        partial void OnGramsChanged();
        /// <summary>
        /// There are no comments for Property Inches in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Inches
        {
            get
            {
                return this._Inches;
            }
            set
            {
                this.OnInchesChanging(value);
                this._Inches = value;
                this.OnInchesChanged();
                this.OnPropertyChanged("Inches");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Inches;
        partial void OnInchesChanging(int value);
        partial void OnInchesChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Gender in the schema.
    /// </summary>
    public enum Gender
    {
        Female = 0,
        Male = 1,
        Other = 2
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.Person as global::AirVinyl.Model.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AirVinyl.Model.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Person> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::AirVinyl.Model.PersonSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.Person as global::AirVinyl.Model.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="personId">The value of personId</param>
        public static global::AirVinyl.Model.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Person> source,
            int personId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PersonId", personId }
            };
            return new global::AirVinyl.Model.PersonSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.VinylRecord as global::AirVinyl.Model.VinylRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AirVinyl.Model.VinylRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.VinylRecord> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::AirVinyl.Model.VinylRecordSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.VinylRecord as global::AirVinyl.Model.VinylRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="vinylRecordId">The value of vinylRecordId</param>
        public static global::AirVinyl.Model.VinylRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.VinylRecord> source,
            int vinylRecordId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "VinylRecordId", vinylRecordId }
            };
            return new global::AirVinyl.Model.VinylRecordSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.PressingDetail as global::AirVinyl.Model.PressingDetailSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AirVinyl.Model.PressingDetailSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.PressingDetail> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::AirVinyl.Model.PressingDetailSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.PressingDetail as global::AirVinyl.Model.PressingDetailSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="pressingDetailId">The value of pressingDetailId</param>
        public static global::AirVinyl.Model.PressingDetailSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.PressingDetail> source,
            int pressingDetailId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PressingDetailId", pressingDetailId }
            };
            return new global::AirVinyl.Model.PressingDetailSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace AirVinyl
{
    /// <summary>
    /// There are no comments for AirVinylContainer in the schema.
    /// </summary>
    public partial class AirVinylContainer : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new AirVinylContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public AirVinylContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Person> People
        {
            get
            {
                if ((this._People == null))
                {
                    this._People = base.CreateQuery<global::AirVinyl.Model.Person>("People");
                }
                return this._People;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Person> _People;
        /// <summary>
        /// There are no comments for VinylRecords in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.VinylRecord> VinylRecords
        {
            get
            {
                if ((this._VinylRecords == null))
                {
                    this._VinylRecords = base.CreateQuery<global::AirVinyl.Model.VinylRecord>("VinylRecords");
                }
                return this._VinylRecords;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.VinylRecord> _VinylRecords;
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToPeople(global::AirVinyl.Model.Person person)
        {
            base.AddObject("People", person);
        }
        /// <summary>
        /// There are no comments for VinylRecords in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToVinylRecords(global::AirVinyl.Model.VinylRecord vinylRecord)
        {
            base.AddObject("VinylRecords", vinylRecord);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""AirVinyl.Model"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Person"">
        <Key>
          <PropertyRef Name=""PersonId"" />
        </Key>
        <Property Name=""PersonId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Email"" Type=""Edm.String"" />
        <Property Name=""FirstName"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""LastName"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""DateOfBirth"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""Gender"" Type=""AirVinyl.Model.Gender"" Nullable=""false"" />
        <Property Name=""NumberOfRecordsOnWishList"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""AmountOfCashToSpend"" Type=""Edm.Decimal"" Nullable=""false"" />
        <NavigationProperty Name=""Friends"" Type=""Collection(AirVinyl.Model.Person)"" />
        <NavigationProperty Name=""VinylRecords"" Type=""Collection(AirVinyl.Model.VinylRecord)"" />
      </EntityType>
      <EntityType Name=""VinylRecord"">
        <Key>
          <PropertyRef Name=""VinylRecordId"" />
        </Key>
        <Property Name=""VinylRecordId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Title"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""Artist"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""CatalogNumber"" Type=""Edm.String"" />
        <Property Name=""Year"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""PressingDetail"" Type=""AirVinyl.Model.PressingDetail"" />
        <NavigationProperty Name=""Person"" Type=""AirVinyl.Model.Person"" />
      </EntityType>
      <EntityType Name=""PressingDetail"">
        <Key>
          <PropertyRef Name=""PressingDetailId"" />
        </Key>
        <Property Name=""PressingDetailId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Grams"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Inches"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Description"" Type=""Edm.String"" Nullable=""false"" />
      </EntityType>
      <EnumType Name=""Gender"">
        <Member Name=""Female"" Value=""0"" />
        <Member Name=""Male"" Value=""1"" />
        <Member Name=""Other"" Value=""2"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""AirVinyl"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""AirVinylContainer"">
        <EntitySet Name=""People"" EntityType=""AirVinyl.Model.Person"">
          <NavigationPropertyBinding Path=""Friends"" Target=""People"" />
          <NavigationPropertyBinding Path=""VinylRecords"" Target=""VinylRecords"" />
        </EntitySet>
        <EntitySet Name=""VinylRecords"" EntityType=""AirVinyl.Model.VinylRecord"">
          <NavigationPropertyBinding Path=""Person"" Target=""People"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
